import {
  Container,
  Box,
  VStack,
  Flex,
  Heading,
  Spacer,
} from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>WeGroup FE assignment</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container maxW={'7xl'}>
          <Heading py='10'>Pokemon showcase</Heading>
          <Flex>
            <Box w='25vw'>
              <VStack>
                <Box
                  w='100%'
                  p={5}
                  shadow='md'
                  borderWidth='1px'
                  flex='1'
                  borderRadius='md'
                >
                  test
                </Box>
                <Box
                  w='100%'
                  p={5}
                  shadow='md'
                  borderWidth='1px'
                  flex='1'
                  borderRadius='md'
                >
                  test
                </Box>
                <Box
                  w='100%'
                  p={5}
                  shadow='md'
                  borderWidth='1px'
                  flex='1'
                  borderRadius='md'
                >
                  test
                </Box>
              </VStack>
            </Box>
            <Spacer />
            <Box w='70vw'>
              <Box
                w='100%'
                p={5}
                shadow='md'
                borderWidth='1px'
                flex='1'
                borderRadius='md'
              >
                box
              </Box>
            </Box>
          </Flex>
        </Container>
      </main>
    </div>
  );
};

export default Home;
