import { Container, Box, Flex, Spacer } from '@chakra-ui/react';
import Head from 'next/head';
import Card from '../components/Card';
import Header from '../components/Header';
import ItemList from '../components/ItemList';
import { useStore } from '../lib/store';

export default function Home() {
  const { active } = useStore();

  return (
    <div>
      <Head>
        <title>WeGroup FE assignment</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container maxW={'7xl'}>
          <Header />
          <Flex>
            <Box w='25vw'>
              <ItemList />
            </Box>
            <Spacer />
            <Box w='70vw'>
              <Card name={active} />
            </Box>
          </Flex>
        </Container>
      </main>
    </div>
  );
}
